#!/usr/bin/env zsh
# Shell switching functions for zmeta

# Function to switch to fish shell
function fish() {
    # Check if fish is being called with arguments
    if [[ $# -gt 0 ]]; then
        # If arguments are provided, pass them to fish
        command fish $@
    else
        # Otherwise, switch to fish shell using our script
        $ZMETA/bin/switch-to-fish
    fi
}

# Function to ensure fish is set up
function setup_fish() {
    # Use our script to set up fish
    $ZMETA/bin/setup-fish $@
}

# Function to make fish the default shell
function use_fish_shell() {
    local fish_path=$(which fish)
    
    if [[ -z "$fish_path" ]]; then
        print -P "%F{red}[ERROR]%f: Fish shell not found. Please install it first."
        return 1
    fi
    
    # Check if fish is already in /etc/shells
    if ! grep -q "$fish_path" /etc/shells; then
        print -P "%F{blue}[INFO]%f: Adding fish to /etc/shells"
        echo "$fish_path" | sudo tee -a /etc/shells
    fi
    
    # Change the default shell
    print -P "%F{blue}[INFO]%f: Changing default shell to fish"
    chsh -s "$fish_path"
    
    print -P "%F{green}[SUCCESS]%f: Default shell changed to fish. Please log out and back in."
}

# Helper to switch back to zsh (for use in fish)
function _switch_to_zsh() {
    exec zsh
}

# Export the zsh switcher function so it can be called from fish
# This will be used by the fish function to switch back to zsh
export -f _switch_to_zsh 2>/dev/null || true  # Suppress error on some zsh versions